# Generated by Django 5.2.7 on 2025-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0004_product_image_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
