# Generated by Django 5.2.7 on 2025-11-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATTN_Backend', '0007_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
